### ISSUE TITLE
Request to add Image icon and Text icon

### ISSUE THREAD

**Issue by Jonas-Cardoso** [jo-te/macish-icons#1]
**Which files or folders shall the icon be applied to?**
Image Files: .jpg, .jpeg, .png, .webp etc...
Text File:  .txt

**Does the icon already exist?**
Icons for image and text don't seem to exist in the plugin icons folder

**Comment by jo-te** [comment]
Thank you for your request.
As of `v0.1.0` which was released just now, both icons are provided.
